# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Install Rust toolchain
RUN apt-get update && apt-get install -y curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV NAME World

# Run manage.py collectstatic (if you have static files)
RUN python manage.py collectstatic --noinput

# Run migrations
RUN python manage.py migrate

# Run the command to start uWSGI
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "hotels.wsgi:application"]
