# Generated by Django 5.0.6 on 2024-06-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(),
        ),
    ]
