# Generated by Django 5.0.6 on 2024-06-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='image\\profile\\userprofile.jpg', null=True, upload_to='accouts/'),
        ),
    ]
