# Generated by Django 5.0.6 on 2024-06-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_city_alter_userprofile_dateofbirth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profileName',
            new_name='user',
        ),
    ]
