# Generated by Django 5.0.6 on 2024-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_dish_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
