# Generated by Django 5.0.6 on 2024-05-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.AddField(
            model_name='dish',
            name='dishImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/image'),
        ),
    ]
