# Generated by Django 5.0.6 on 2024-05-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_dish_image_dish_dishimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurants',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishImage',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='images/'),
        ),
    ]
