# Generated by Django 5.0.6 on 2024-06-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_restaurants_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='locations',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='restaurantName',
            field=models.CharField(max_length=200),
        ),
    ]
