# Generated by Django 5.0.6 on 2024-06-11 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_dish_description_alter_dish_dishname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_charges', models.IntegerField(default=50)),
                ('total_charges', models.IntegerField()),
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='base.dish')),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
