# Generated by Django 5.0.6 on 2024-06-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='location',
            field=models.CharField(default='Kharadi PUNE 14', max_length=200),
        ),
    ]
