# Generated by Django 5.0.6 on 2024-06-14 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.dish'),
        ),
        migrations.AlterField(
            model_name='images',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='base.restaurants'),
        ),
    ]
