# Generated by Django 5.0.6 on 2024-06-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_images_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.restaurants'),
        ),
    ]
