# Generated by Django 5.0.6 on 2024-06-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reviews',
            new_name='review',
        ),
    ]
