# Generated by Django 5.0.6 on 2024-06-23 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_reviews_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.dish'),
        ),
    ]
