# Generated by Django 5.0.6 on 2024-06-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_dish_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-id']},
        ),
    ]
