# Generated by Django 5.0.6 on 2024-06-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_reviews_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
