# Generated by Django 5.0.6 on 2024-07-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_reviews_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.hotel'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.hotel'),
        ),
    ]
