indian_dishes = [
#    "butter chicken",
#     "Biryani",
    "Paneer Tikka",
    "masala Dosa",
    "Samosa",
    # "Tandoori Chicken",
    "Chole Bhature",
    "Palak Paneer",
    "Aloo Gobi",
    "Pani Puri",
"pizza",
    "Rogan Josh",
    "suzi"
    # "Dal Makhani",
    # "Pav Bhaji",
    # "Fish Curry",
    # "Chicken Biryani",
    # "Pakora",
    # "Korma",
    # "Gulab Jamun",
    # "Jalebi",
    # "Papdi Chaat",
    # "Malai Kofta",
    # "Chicken Curry",
    # "Aloo Paratha",
    # "Rasgulla",
    # "Dhokla",
    # "Mutton Curry",
    # "Pulao",
    # "Raita",
    # "Chaat",
    # "Kadai Paneer",
    # "Bhindi Masala",
    # "Chicken Korma",
    # "Tandoori Roti",
    # "Matar Paneer",
    # "Chana Masala",
    # "Kofta",
    # "Samosa Chaat",
    # "Shahi Paneer"
]
